application: fluted-reporter-514
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /log_sale
  script: SaleDBLogHandler.application
- url: /excel_logger
  script: SaleExcelLoghandlerCron.application
  login: admin